# Generated by scripts/update-homebrew.py. Edit scripts/aigc.rb.in instead.
class Aigc < Formula
  desc "Local garbage collector for development storage on macOS"
  homepage "https://github.com/MyhreS/AI-Garbage-Collector"
  version "0.7.0"
  license "MIT"

  depends_on macos: :ventura

  on_macos do
    on_arm do
      url "https://github.com/MyhreS/AI-Garbage-Collector/releases/download/v0.7.0/aigc-aarch64-apple-darwin.tar.gz"
      sha256 "3651ebff36553f82b974206a0d34c733caea3d661b8c4fd92019b17d13027dfd"
    end

    on_intel do
      url "https://github.com/MyhreS/AI-Garbage-Collector/releases/download/v0.7.0/aigc-x86_64-apple-darwin.tar.gz"
      sha256 "4e7a8eddde71ebf96e198c6625126152bf1d0f68bbfcde82adda1a6ffef09af2"
    end
  end

  def install
    bin.install "aigc"
    doc.install "README.md"
    doc.install "docs" if Dir.exist?("docs")
  end

  service do
    name macos: "io.aigc.collector"
    run [opt_bin/"aigc", "collect"]
    run_type :interval
    interval 3600
    run_at_load true
    working_dir Dir.home
    environment_variables HOME: Dir.home,
                          PATH: "#{Dir.home}/.local/bin:/usr/local/bin:#{std_service_path_env}"
  end

  def caveats
    <<~EOS
      A direct brew install does not start cleanup. To start the hourly collector:
        brew services start myhres/aigc/aigc

      For one-command installation and automatic startup, use the Brewfile:
        curl -fsSL https://raw.githubusercontent.com/MyhreS/AI-Garbage-Collector/main/Brewfile | brew bundle --file=-

      Inspect resources with:
        aigc status

      If switching from the standalone installer, stop its service first:
        aigc service uninstall
      Then use brew services to manage the collector. Do not use sudo.
    EOS
  end
end
