# Generated by scripts/update-homebrew.py. Edit scripts/aigc.rb.in instead.
class Aigc < Formula
  desc "Local garbage collector for development storage on macOS"
  homepage "https://github.com/MyhreS/AI-Garbage-Collector"
  version "0.7.2"
  license "MIT"

  depends_on macos: :ventura

  on_macos do
    on_arm do
      url "https://github.com/MyhreS/AI-Garbage-Collector/releases/download/v0.7.2/aigc-aarch64-apple-darwin.tar.gz"
      sha256 "887b712e23d127a7a5041e3dd4c0152efd009048f50e88050d6a5186d190c7a4"
    end

    on_intel do
      url "https://github.com/MyhreS/AI-Garbage-Collector/releases/download/v0.7.2/aigc-x86_64-apple-darwin.tar.gz"
      sha256 "6bc18f414c9d17112f47ed0ea775951448cce122e58872bcc9c46d090d039956"
    end
  end

  def install
    bin.install "aigc"
    doc.install "README.md"
    doc.install "docs" if Dir.exist?("docs")
  end

  service do
    name macos: "io.aigc.collector"
    run [opt_bin/"aigc", "collect"]
    run_type :interval
    interval 3600
    run_at_load true
    working_dir Dir.home
    environment_variables HOME: Dir.home,
                          PATH: "#{Dir.home}/.local/bin:/usr/local/bin:#{std_service_path_env}"
  end

  def caveats
    <<~EOS
      A direct brew install does not start cleanup. To start the hourly collector:
        brew services start myhres/aigc/aigc

      For one-command installation and automatic startup, use the Brewfile:
        curl -fsSL https://raw.githubusercontent.com/MyhreS/AI-Garbage-Collector/main/Brewfile | brew bundle --file=-

      Inspect resources with:
        aigc status

      If switching from the standalone installer, stop its service first:
        aigc service uninstall
      Then use brew services to manage the collector. Do not use sudo.
    EOS
  end
end
